"""empty message

Revision ID: 5599a024e77e
Revises: b542f0fb5663
Create Date: 2022-02-12 11:13:12.561890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5599a024e77e'
down_revision = 'b542f0fb5663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('character', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('character', 'hair_color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('character', 'skin_color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('character', 'eye_color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('character', 'birth_year',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('character', 'gender',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('character', 'created',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('character', 'edited',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('character', 'homeworld',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('character', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'homeworld',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('character', 'edited',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('character', 'created',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('character', 'gender',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('character', 'birth_year',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('character', 'eye_color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('character', 'skin_color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('character', 'hair_color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('character', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('character', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
