"""empty message

Revision ID: b542f0fb5663
Revises: 67154473da7e
Create Date: 2022-02-12 11:06:50.823611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b542f0fb5663'
down_revision = '67154473da7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('planet', 'terrain',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('planet', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'created',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planet', 'edited',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planet', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'edited',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planet', 'created',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planet', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'terrain',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('planet', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
